name: Test

on:
  push:
    branches: [migrate-to-mihomo, main]
  pull_request:
    branches: [migrate-to-mihomo, main]

env:
  GO_VERSION: "^1.22"

jobs:
  unit-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: go test -tags with_gvisor -count=1 -timeout 120s ./...

  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build CLI
        run: go build -tags with_gvisor -o mihomo .
      - name: Build c-shared
        run: |
          go install src.techknowlogick.com/xgo@latest
          xgo --targets=linux/amd64 -tags="with_gvisor" -buildmode=c-shared -out=libclash.so ./bind/desktop

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26
          add-to-path: false
          local-cache: true
      - name: Build Android arm64
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go get golang.org/x/mobile/bind
          gomobile init
          gomobile bind -tags="with_gvisor" -target=android/arm64 -androidapi 29 -javapkg com.web3jsq -o libclash.aar github.com/metacubex/mihomo/bind/mobile

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build iOS
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go get golang.org/x/mobile/bind
          gomobile init
          gomobile bind -tags="with_gvisor" -target=ios -o libclash.xcframework github.com/metacubex/mihomo/bind/mobile
